export const testTeams = {
  name: '2020 NCAA Mens Basketball',
  teams: [
    {
      name: 'Minnesota',
      seed: 1,
      group: 'W',
      points: 0,
      inTournament: true,
      nextMatch: '2W Michigan',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
    {
      name: 'Michigan',
      seed: 2,
      group: 'W',
      points: 0,
      inTournament: true,
      nextMatch: '2W Minnesota',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
    {
      name: 'Michigan State',
      seed: 3,
      group: 'W',
      points: 0,
      inTournament: true,
      nextMatch: '4W Wisconsin',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
    {
      name: 'Wisconsin',
      seed: 4,
      group: 'W',
      points: 0,
      inTournament: true,
      nextMatch: '3W MSU',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
    {
      name: 'Rutgers',
      seed: 5,
      group: 'W',
      points: 0,
      inTournament: true,
      nextMatch: '6W PSU',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
    {
      name: 'Penn State',
      seed: 6,
      group: 'W',
      points: 0,
      inTournament: true,
      nextMatch: '2W Michigan',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
    {
      name: 'Indiana',
      seed: 7,
      group: 'W',
      points: 0,
      inTournament: true,
      nextMatch: '8W NW',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
    {
      name: 'Indiana',
      seed: 8,
      group: 'W',
      points: 0,
      inTournament: true,
      nextMatch: '2W IU',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
  ],
};
