export const testTeams = {
  name: '2020 NCAA Mens Basketball',
  groups: ['WEST', 'EAST'],
  teams: [
    {
      name: 'Minnesota',
      seed: 1,
      groupAbbr: 'W',
      group: 'WEST',
      points: 0,
      inTournament: true,
      nextMatch: '2W Michigan',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
    {
      name: 'Michigan',
      seed: 2,
      groupAbbr: 'W',
      group: 'WEST',
      points: 0,
      inTournament: true,
      nextMatch: '2W Minnesota',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
    {
      name: 'Michigan State',
      seed: 3,
      groupAbbr: 'W',
      group: 'WEST',
      points: 0,
      inTournament: true,
      nextMatch: '4W Wisconsin',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
    {
      name: 'Wisconsin',
      seed: 4,
      groupAbbr: 'W',
      group: 'WEST',
      points: 0,
      inTournament: true,
      nextMatch: '3W MSU',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
    {
      name: 'Rutgers',
      seed: 5,
      groupAbbr: 'W',
      group: 'WEST',
      points: 0,
      inTournament: true,
      nextMatch: '6W PSU',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
    {
      name: 'Penn State',
      seed: 6,
      groupAbbr: 'W',
      group: 'WEST',
      points: 0,
      inTournament: true,
      nextMatch: '2W Michigan',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
    {
      name: 'Indiana',
      seed: 7,
      groupAbbr: 'W',
      group: 'WEST',
      points: 0,
      inTournament: true,
      nextMatch: '8W NW',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
    {
      name: 'Indiana',
      seed: 8,
      groupAbbr: 'W',
      group: 'WEST',
      points: 0,
      inTournament: true,
      nextMatch: '2W IU',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
    {
      name: 'Duke',
      seed: 1,
      groupAbbr: 'E',
      group: 'EAST',
      points: 0,
      inTournament: true,
      nextMatch: '2E UNC',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
    {
      name: 'UNC',
      seed: 2,
      groupAbbr: 'E',
      group: 'EAST',
      points: 0,
      inTournament: true,
      nextMatch: '1E Duke',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
    {
      name: 'Georgia Tech',
      seed: 3,
      groupAbbr: 'E',
      group: 'EAST',
      points: 0,
      inTournament: true,
      nextMatch: '4E Syracuse',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
    {
      name: 'Syracuse',
      seed: 4,
      groupAbbr: 'E',
      group: 'EAST',
      points: 0,
      inTournament: true,
      nextMatch: '3E MSU',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
    {
      name: 'VCU',
      seed: 5,
      groupAbbr: 'E',
      group: 'EAST',
      points: 0,
      inTournament: true,
      nextMatch: '6E Clemson',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
    {
      name: 'Clemson',
      seed: 6,
      groupAbbr: 'E',
      group: 'EAST',
      points: 0,
      inTournament: true,
      nextMatch: '2W VCU',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
    {
      name: 'South Carolina',
      seed: 7,
      groupAbbr: 'E',
      group: 'EAST',
      points: 0,
      inTournament: true,
      nextMatch: '8W Florida',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
    {
      name: 'Florida',
      seed: 8,
      groupAbbr: 'E',
      group: 'EAST',
      points: 0,
      inTournament: true,
      nextMatch: '2W South Carolina',
      details: {
        conference: 'Big Ten',
        record: '30-1',
        conferenceRecord: '20-0',
        nonConferenceRecord: '10-1',
        ranking: '1',
      },
      owner: '',
      ownerName: '',
    },
  ],
};
